import type { Locale } from "@/types/catalog";

const de = {
  nav: { home: "Startseite", shop: "Shop", categories: "Kategorien", about: "Über LABONI", contact: "Kontakt", search: "Suche", account: "Konto", cart: "Warenkorb" },
  common: { discover: "Jetzt entdecken", viewProduct: "Produkt ansehen", addToCart: "In den Warenkorb", unavailable: "Derzeit nicht bestellbar", from: "ab", products: "Produkte", close: "Schliessen", continueShopping: "Weiter einkaufen", checkout: "Zur Kasse", quantity: "Menge", remove: "Entfernen", total: "Gesamt", subtotal: "Zwischensumme", shipping: "Versand", tax: "Steuern", back: "Zurück" },
  home: { heroTitle: "Gutes Design gehört zum Zusammenleben.", heroBody: "Ausgewählte LABONI Produkte für Hunde und Menschen, die Komfort, Funktion und eine ruhige Formensprache schätzen.", categories: "Nach Kategorie einkaufen", selected: "Für den Alltag ausgewählt", storyTitle: "Für Hund und Halter gedacht", storyBody: "LABONI verbindet durchdachte Gestaltung, ausgewählte Materialien und handwerkliche Verarbeitung mit den Bedürfnissen des Hundealltags.", benefits: ["Verifizierte Produktdaten", "Ausgewählte Materialien", "In Zürich kuratiert", "14 Tage Rückgabefrist"] },
  shop: { title: "Kollektion", intro: "Entdecken Sie die kuratierte LABONI Auswahl.", filter: "Filter", sort: "Sortieren", recommended: "Empfohlen", lowHigh: "Preis aufsteigend", highLow: "Preis absteigend", name: "Name", availability: "Verfügbarkeit", inStock: "Sofort verfügbar" },
  product: { sku: "Art.-Nr.", stock: "Auf Lager", outOfStock: "Nicht verfügbar", selectOptions: "Bitte wählen Sie alle Optionen", verified: "Produktangaben aus LABONI Katalog und Website", details: "Produktdetails", material: "Material", size: "Grösse", color: "Farbe", fabric: "Stoff", mattress: "Matratze", configuration: "Ausführung", capacity: "Inhalt" },
  cart: { title: "Warenkorb", empty: "Ihr Warenkorb ist noch leer.", note: "Preise und Bestand werden vor dem Checkout serverseitig geprüft." },
  checkout: { title: "Sicher zur Bestellung", contact: "Kontakt", delivery: "Lieferadresse", payment: "Zahlung", review: "Prüfen", firstName: "Vorname", lastName: "Nachname", email: "E-Mail", phone: "Telefon", street: "Strasse", houseNumber: "Hausnummer", postalCode: "PLZ", city: "Ort", country: "Land", billingSame: "Rechnungsadresse entspricht Lieferadresse", continue: "Versand prüfen", unavailable: "Für diese Adresse ist noch keine Versandart konfiguriert.", secure: "Kartendaten werden ausschliesslich beim Zahlungsanbieter verarbeitet." },
};

const en: typeof de = {
  nav: { home: "Home", shop: "Shop", categories: "Categories", about: "About LABONI", contact: "Contact", search: "Search", account: "Account", cart: "Cart" },
  common: { discover: "Shop now", viewProduct: "View product", addToCart: "Add to cart", unavailable: "Currently unavailable", from: "from", products: "Products", close: "Close", continueShopping: "Continue shopping", checkout: "Checkout", quantity: "Quantity", remove: "Remove", total: "Total", subtotal: "Subtotal", shipping: "Shipping", tax: "Tax", back: "Back" },
  home: { heroTitle: "Good design belongs in everyday life.", heroBody: "Selected LABONI products for dogs and people who value comfort, function and a quiet design language.", categories: "Shop by category", selected: "Selected for daily life", storyTitle: "Made for dogs and their people", storyBody: "LABONI brings considered design, selected materials and craftsmanship together with the needs of everyday life with a dog.", benefits: ["Verified product data", "Selected materials", "Curated in Zurich", "14-day return period"] },
  shop: { title: "Collection", intro: "Discover the curated LABONI selection.", filter: "Filter", sort: "Sort", recommended: "Recommended", lowHigh: "Price low to high", highLow: "Price high to low", name: "Name", availability: "Availability", inStock: "Available now" },
  product: { sku: "Article no.", stock: "In stock", outOfStock: "Unavailable", selectOptions: "Please select all options", verified: "Product information verified against LABONI catalog and website", details: "Product details", material: "Material", size: "Size", color: "Colour", fabric: "Fabric", mattress: "Mattress", configuration: "Configuration", capacity: "Capacity" },
  cart: { title: "Your cart", empty: "Your cart is empty.", note: "Prices and stock are validated on the server before checkout." },
  checkout: { title: "Secure checkout", contact: "Contact", delivery: "Delivery address", payment: "Payment", review: "Review", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone", street: "Street", houseNumber: "House number", postalCode: "Postal code", city: "City", country: "Country", billingSame: "Billing address is the same as delivery", continue: "Check shipping", unavailable: "No shipping method has been configured for this address yet.", secure: "Card details are processed exclusively by the payment provider." },
};

export function getDictionary(locale: Locale) {
  return locale === "en" ? en : de;
}
