import type { Locale } from "@/types/catalog";

const de = {
  nav: { home: "Startseite", shop: "Shop", categories: "Kategorien", about: "Über uns", contact: "Kontakt", search: "Suche", account: "Konto", cart: "Warenkorb" },
  common: { discover: "Jetzt entdecken", viewProduct: "Produkt ansehen", addToCart: "In den Warenkorb", unavailable: "Derzeit nicht bestellbar", from: "ab", products: "Produkte", close: "Schliessen", continueShopping: "Weiter einkaufen", checkout: "Zur Kasse", quantity: "Menge", remove: "Entfernen", total: "Gesamt", subtotal: "Zwischensumme", shipping: "Versand", tax: "Steuern", back: "Zurück" },
  home: { heroTitle: "Schöner leben. Gemeinsam.", heroBody: "Ausgewählte Dinge für Hunde und Menschen, die Komfort, Funktion und gutes Design schätzen.", categories: "Für jeden gemeinsamen Moment", selected: "Unsere Bestseller", storyTitle: "Mit Blick für das Wesentliche", storyBody: "Anna's Dog & More kuratiert langlebige Produkte, die sich selbstverständlich in ein schönes Zuhause einfügen.", benefits: ["Sorgfältig kuratiert", "Hochwertige Materialien", "Persönlich in Zürich", "Sichere Zahlung"] },
  shop: { title: "Kollektion", intro: "Entdecken Sie ausgewählte Begleiter für ein gutes Leben mit Hund.", filter: "Filter", sort: "Sortieren", recommended: "Empfohlen", lowHigh: "Preis aufsteigend", highLow: "Preis absteigend", name: "Name", newest: "Neueste", price: "Preis", material: "Material", color: "Farbe", size: "Grösse", availability: "Verfügbarkeit", inStock: "Sofort verfügbar" },
  product: { sku: "Art.-Nr.", stock: "Auf Lager", outOfStock: "Bestand wird bestätigt", selectOptions: "Bitte wählen Sie alle Optionen", verified: "Sorgfältig ausgewählte Produktdetails", details: "Produktdetails", material: "Material", size: "Grösse", color: "Farbe", fabric: "Stoff", mattress: "Matratze", configuration: "Ausführung", capacity: "Inhalt", care: "Pflege" },
  cart: { title: "Warenkorb", empty: "Ihr Warenkorb ist noch leer.", note: "Preise und Bestand werden vor dem Checkout serverseitig geprüft." },
  checkout: { title: "Sicher zur Bestellung", contact: "Kontakt", delivery: "Lieferadresse", payment: "Zahlung", review: "Prüfen", firstName: "Vorname", lastName: "Nachname", email: "E-Mail", phone: "Telefon", street: "Strasse", houseNumber: "Hausnummer", postalCode: "PLZ", city: "Ort", country: "Land", billingSame: "Rechnungsadresse entspricht Lieferadresse", continue: "Versand prüfen", unavailable: "Für diese Adresse ist noch keine Versandart konfiguriert.", secure: "Kartendaten werden ausschliesslich beim Zahlungsanbieter verarbeitet." },
};

const en: typeof de = {
  nav: { home: "Home", shop: "Shop", categories: "Categories", about: "About us", contact: "Contact", search: "Search", account: "Account", cart: "Cart" },
  common: { discover: "Shop now", viewProduct: "View product", addToCart: "Add to cart", unavailable: "Currently unavailable", from: "from", products: "Products", close: "Close", continueShopping: "Continue shopping", checkout: "Checkout", quantity: "Quantity", remove: "Remove", total: "Total", subtotal: "Subtotal", shipping: "Shipping", tax: "Tax", back: "Back" },
  home: { heroTitle: "Living beautifully. Together.", heroBody: "Selected pieces for dogs and people who value comfort, function and thoughtful design.", categories: "For every shared moment", selected: "Our bestsellers", storyTitle: "An eye for what matters", storyBody: "Anna's Dog & More curates enduring products that feel naturally at home in considered interiors.", benefits: ["Carefully curated", "Quality materials", "Personal service in Zurich", "Secure payment"] },
  shop: { title: "Collection", intro: "Discover selected companions for a good life with dogs.", filter: "Filter", sort: "Sort", recommended: "Recommended", lowHigh: "Price low to high", highLow: "Price high to low", name: "Name", newest: "Newest", price: "Price", material: "Material", color: "Colour", size: "Size", availability: "Availability", inStock: "Available now" },
  product: { sku: "Article no.", stock: "In stock", outOfStock: "Stock being confirmed", selectOptions: "Please select all options", verified: "Carefully selected product details", details: "Product details", material: "Material", size: "Size", color: "Colour", fabric: "Fabric", mattress: "Mattress", configuration: "Configuration", capacity: "Capacity", care: "Care" },
  cart: { title: "Your cart", empty: "Your cart is empty.", note: "Prices and stock are validated on the server before checkout." },
  checkout: { title: "Secure checkout", contact: "Contact", delivery: "Delivery address", payment: "Payment", review: "Review", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone", street: "Street", houseNumber: "House number", postalCode: "Postal code", city: "City", country: "Country", billingSame: "Billing address is the same as delivery", continue: "Check shipping", unavailable: "No shipping method has been configured for this address yet.", secure: "Card details are processed exclusively by the payment provider." },
};

export function getDictionary(locale: Locale) {
  return locale === "en" ? en : de;
}
