import Image from "next/image";
import Link from "next/link";
import { isLocale } from "@/lib/i18n/config";

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) return null;
  const de = locale === "de";
  return <div className="editorial-page"><header className="editorial-hero"><div><p>Anna&apos;s Dog & More</p><h1>{de ? "Gutes für Hunde. Schön für Zuhause." : "Good for dogs. Beautiful at home."}</h1></div><Image src="https://laboni.design/media/image/LABONI_Polsterbett_Teddy_beige_L_24.jpg" alt={de ? "Hund in einem weichen TEDDY Hundebett" : "Dog resting in a soft TEDDY dog bed"} width={900} height={900} priority /></header><section className="editorial-copy"><h2>{de ? "Unsere Geschichte" : "Our story"}</h2><div><p>{de ? "Anna's Dog & More ist ein unabhängiges Fachgeschäft in Zürich. Wir wählen Dinge aus, die den Alltag mit Hund angenehmer machen und sich zugleich selbstverständlich in ein schönes Zuhause einfügen." : "Anna's Dog & More is an independent specialist shop in Zurich. We select objects that make life with dogs more comfortable and feel naturally at home in considered interiors."}</p><p>{de ? "Unser Sortiment verbindet langlebige Materialien, klare Gestaltung und praktische Pflege. Persönliche Beratung und nachvollziehbare Produktinformationen stehen dabei im Mittelpunkt." : "Our collection brings together durable materials, clear design and practical care. Personal advice and precise product information remain central to everything we do."}</p></div></section><section className="about-values"><article><strong>{de ? "Gestaltung" : "Design"}</strong><p>{de ? "Eine klare Formensprache für Produkte, die sichtbar im Zuhause leben." : "A clear design language for products that live visibly in the home."}</p></article><article><strong>{de ? "Komfort" : "Comfort"}</strong><p>{de ? "Ausgewählte Produkte orientieren sich an den Bedürfnissen von Hund und Halter." : "Selected products respond to the needs of dogs and their people."}</p></article><article><strong>{de ? "Langlebigkeit" : "Longevity"}</strong><p>{de ? "Austauschbare Komponenten und belastbare Materialien für viele gemeinsame Jahre." : "Replaceable components and durable materials for years of life together."}</p></article></section><section className="brand-note"><div><h2>{de ? "Premium Marken bei Anna's Dog & More" : "Premium brands at Anna's Dog & More"}</h2><p>{de ? "LABONI ist eine der Marken in unserer Auswahl. Die Kollektion steht für funktionale Hundemöbel, innovative Materialien und handwerkliche Verarbeitung." : "LABONI is one of the brands in our selection. Its collection is known for functional dog furniture, innovative materials and considered craftsmanship."}</p></div><strong>LABONI</strong></section><div className="editorial-cta"><h2>{de ? "Die Kollektion entdecken" : "Explore the collection"}</h2><Link className="button primary-button" href={`/${locale}/shop`}>{de ? "Zum Shop" : "Shop now"}</Link></div></div>;
}
