import Image from "next/image";
import Link from "next/link";
import { isLocale } from "@/lib/i18n/config";

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) return null;
  const de = locale === "de";
  return <div className="editorial-page"><header className="editorial-hero"><div><p>LABONI × Anna&apos;s Dog & More</p><h1>{de ? "Dinge, die Hundeleben schöner machen." : "Objects that make life with dogs better."}</h1></div><Image src="https://laboni.design/media/image/thumbnail/LABONI_Polsterbett_Teddy_beige_L_24_600x600.jpg" alt={de ? "LABONI Hundebett mit weichem TEDDY Bezug" : "LABONI dog bed with soft TEDDY cover"} width={700} height={700} priority /></header><section className="editorial-copy"><h2>{de ? "Unsere Auswahl" : "Our selection"}</h2><div><p>{de ? "LABONI entwickelt Produkte, bei denen Gestaltung, Funktion und Pflegeleichtigkeit zusammen gedacht werden. Das Sortiment reicht von handgeknüpften Baumwollspielzeugen bis zu Betten mit austauschbaren Bezügen und Matratzen." : "LABONI develops products that bring design, function and easy care together. The range spans hand-knotted cotton toys and beds with replaceable covers and mattresses."}</p><p>{de ? "Anna's Dog & More kuratiert diese Produkte für Kundinnen und Kunden in Zürich und darüber hinaus. Artikelnummern, Materialien und Varianten werden vor der Veröffentlichung gegen die aktuelle LABONI Website und die bereitgestellten Kataloge geprüft." : "Anna's Dog & More curates these products for customers in Zurich and beyond. Article numbers, materials and variants are checked against the current LABONI website and supplied catalogues before publication."}</p></div></section><section className="about-values"><article><strong>{de ? "Gestaltung" : "Design"}</strong><p>{de ? "Eine klare Formensprache für Produkte, die sichtbar im Zuhause leben." : "A clear design language for products that live visibly in the home."}</p></article><article><strong>{de ? "Komfort" : "Comfort"}</strong><p>{de ? "Ausgewählte Produkte orientieren sich an den Bedürfnissen von Hund und Halter." : "Selected products respond to the needs of dogs and their people."}</p></article><article><strong>{de ? "Genauigkeit" : "Accuracy"}</strong><p>{de ? "Kein erfundener Bestand, keine pauschalen Varianten, keine stillen Preisumrechnungen." : "No invented stock, generic variants or silent currency conversion."}</p></article></section><div className="editorial-cta"><h2>{de ? "Die Kollektion entdecken" : "Explore the collection"}</h2><Link className="button primary-button" href={`/${locale}/shop`}>{de ? "Zum Shop" : "Shop now"}</Link></div></div>;
}
